### ISSUE TITLE
C++ code won't compile

### ISSUE THREAD

**Issue by MattBashton** [AstraZeneca-NGS/disambiguate#10]
Hi I'm attempting to compile the C++ version on Ubuntu 16.04 and the current clone of bamtools and it fails, any suggestions?

`g++ -I /usr/local/include/bamtools/ -I./ -L /usr/local/lib/ -o ngs_disambiguate dismain.cpp -lz -lbamtools  
                                                                                                                  /usr/local/lib//libbamtools.a(BgzfStream_p.cpp.o): In function `BamTools::Internal::BgzfStream::DeflateBlock(int)':
BgzfStream_p.cpp:(.text+0x1a9): undefined reference to `deflateEnd'
BgzfStream_p.cpp:(.text+0x211): undefined reference to `deflateInit2_'
BgzfStream_p.cpp:(.text+0x22a): undefined reference to `deflate'
BgzfStream_p.cpp:(.text+0x240): undefined reference to `deflateEnd'
BgzfStream_p.cpp:(.text+0x279): undefined reference to `crc32'
BgzfStream_p.cpp:(.text+0x286): undefined reference to `crc32'
/usr/local/lib//libbamtools.a(BgzfStream_p.cpp.o): In function `BamTools::Internal::BgzfStream::InflateBlock(unsigned long const&)':
BgzfStream_p.cpp:(.text+0xe8c): undefined reference to `inflateInit2_'
BgzfStream_p.cpp:(.text+0xe9d): undefined reference to `inflate'
BgzfStream_p.cpp:(.text+0xeae): undefined reference to `inflateEnd'
BgzfStream_p.cpp:(.text+0xf72): undefined reference to `inflateEnd'
BgzfStream_p.cpp:(.text+0xff4): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status`

**Comment by MattBashton** [comment]
Taking a hint from the miniconda issues, I figured that you're only tested / developed your code against version 2.4.0 of bamtools, using this particular version I was able to get the code to compile. 
 However you should possibly update the documentation to state that this version specifically needs to be used at compile time.

**Comment by mjafin** [comment]
Hi @MattBashton thanks for the bug report and also thanks for pointing us in the right direction as for the underlying issue. I don't currently have the resource to address newer versions of bamtools but if you're happy with us explicitly requiring `2.4.0` I can add a mention. Even better, if you can provide a pull request to fix the issue that'd be much appreciated. I'll look at the associated ticket on bioconda issues.

**Comment by MattBashton** [comment]
Hi Miika, I've edited the README.md to note the version requirement and submitted a pull request, the bioconda issue has now been fixed.

**Comment by mjafin** [comment]
@MattBashton thank you for that. If you or anyone you know has any expertise with newer versions of bamtools I'm happy to accept a pull request to support >`2.4`

**Comment by MattBashton** [comment]
I'll ask around, it's not an API I've used but pretty sure someone out there might have an intrest in keeping up with the current version.
