### ISSUE TITLE
Can Disambiguate work on GSNAP-generated BAM files and single-end reads?

### ISSUE THREAD

**Issue by apfuentes** [AstraZeneca-NGS/disambiguate#18]
Hi @mjafin @roryk @serverhorror,
Thanks for developing Disambiguate.

I have single-end 50 bp RNA-seq reads that were mapped using the aligner GSNAP. I was recommend to use your tool to disambiguate F1 reads that were separately mapped to the genome of their parents (for ASE - allele specific expression - analysis).

From the documentation, I understand that Disambiguate is implemented for BAM files generated by these 4 aligners: `Tophat`, `Hisat2`, `BWA`, and `STAR`. The program assigns the reads on a per-pair basis, based on the highest quality alignment of the read pair. For `Tophat` and `Hisat2`, the sum of the flags `XO`, `NM` and `NH` is evaluated and the lowest sum wins the paired end reads. For equal scores, the reads are assigned as ambiguous. For `STAR` and `bwa`, the program disambiguates by tags `AS `(alignment score, higher better), followed by `NM` (edit distance, lower better).

- To know which aligner option I should use for our BAM files, I checked out the GMAP/GSNAP documentation to verify which flags GSNAP generates. GSNAP adds `XO` and `NM` flags but I do not find `NH` and `AS` (http://research-pub.gene.com/gmap/src/README). 

I confirmed the BAM files do not have NH flag with the commands:
```
samtools view -H Sample_A.bam | grep “NH:i”
samtools view -H Sample_B.bam | grep "NH:i”
samtools view -H Sample_C.bam | grep "NH:i"
```
No hits.

So, it seems I could use the options `tophat` or `hisat2`, but wanted to ask:
- **Question 1:** Will Disambiguate run into problems when not finding the NH flag?
- **Question 2:** How to make Disambiguate work on single-end reads? Which part of the script should be modified to make this possible?

Thanks for any help!

Angela

**Comment by mjafin** [comment]
Hi Angela,
Thanks for the message and interest in our algorithm. 

You can probably get away with single end reads but it'd be a matter of trying it out what happens without the NH tag: 
https://github.com/AstraZeneca-NGS/disambiguate/blob/master/disambiguate.py#L62

If you're ok using the Python version (it can be slow vs C++) you could simply modify line 62 and remove the NH tag from the summation. This might affect the performance of the algorithm a little bit.

Hope this helps. Let me know how it goes. 

Best wishes, 
Miika

**Comment by apfuentes** [comment]
Hi @mjafin 
Many thanks for your prompt response!

Yes, I am using the python version of the code, so it will be easy to modify Ln 62 :)

- **Question**: would it be possible to use alternative information from the GSNAP-generated bam file that perhaps could provide similar info than the missing NH tag?

The NH tag tells how many times a read name occurs, so it will be 1 for uniquely mapped reads and >1 for multi-mapping reads.

Among the flags generated by GSNAP: http://research-pub.gene.com/gmap/src/README (go to special SAM flags), perhaps X2 could help distinguish from uniquely mapped reads from multi-mappers, but not sure what other flag could be useful:

X2: The second best XQ score among all multimapping alignments for a
given read.  If there is only a single alignment, this value is 0.
XQ: A non-normalized mapping quality score

Or maybe the bit code from sam files: multi-mapped reads contain bit of 0x100 in their FLAG tag. Thoughts?

Thanks!

Angela

**Comment by mjafin** [comment]
@apfuentes what you could do is take some mouse reads (any public data, take just read 1 to mimic your data) like we did in the paper and try out how much adding or removing a tag from the algorithm affects specificity. Then repeat for human reads on sensitivity. You might find with a little bit of trial and error a useful new tag or that the two available tags are completely sufficient.
