### ISSUE TITLE
C++ version niceties

### ISSUE THREAD

**Issue by roryk** [AstraZeneca-NGS/disambiguate#2]
Hi Miika,

It would be sweet if the C++ version did a couple of nice things, it seems like it doesn't throw an abnormal exit code when it tries to make the BAM files and can't. It would also be super nice if it made the output directory if it does not exist already. Any shot of
those things happening?

**Comment by roryk** [comment]
Thanks! Check out this necromantic issue close.

**Comment by mjafin** [comment]
Better late..!
