### ISSUE TITLE
Samtools sort syntax

### ISSUE THREAD

**Issue by bioinfomagician** [AstraZeneca-NGS/disambiguate#3]
Hi, 

I noticed that when I attempted to used this tool on files that were not already name sorted, that it will run into errors. As a test, I order sorted the test bam files included with this tool. 

`python disambiguate.py test/human.sorted.bam test/mouse.sorted.bam`

> Traceback (most recent call last):
>   File "disambiguate.py", line 350, in <module>
>     main(args)
>   File "disambiguate.py", line 181, in main
>     pysam.sort("-n","-m","2000000000",humanfilename,humanfilenamesorted.replace(".bam",""))
>   File "/usr/local/lib/python2.7/site-packages/pysam/utils.py", line 75, in __call__
>     stderr))
> pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files\nUsage: samtools sort [options...] [in.bam]\nOptions:\n  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)\n  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]\n  -n         Sort by read name\n  -o FILE    Write final output to FILE rather than standard output\n  -T PREFIX  Write temporary files to PREFIX.nnnn.bam\n  -@, --threads INT\n             Set number of sorting and compression threads [1]\n      --input-fmt-option OPT[=VAL]\n               Specify a single input file format option in the form\n               of OPTION or OPTION=VALUE\n  -O, --output-fmt FORMAT[,OPT[=VAL]]...\n               Specify output format (SAM, BAM, CRAM)\n      --output-fmt-option OPT[=VAL]\n               Specify a single output file format option in the form\n               of OPTION or OPTION=VALUE\n      --reference FILE\n               Reference sequence FASTA FILE [null]\n'
> 

I guessed that this was because the pysam sort call was using an older syntax which is no longer compatible with samtools .1.3.1. So, I changed the following lines

`pysam.sort("-n","-m","2000000000",humanfilename,humanfilenamesorted.replace(".bam",""))`
`pysam.sort("-n","-m","2000000000",mousefilename,mousefilenamesorted.replace(".bam",""))`

to 

`pysam.sort("-n","-m","2000000000","-o",humanfilenamesorted,humanfilename)`
`pysam.sort("-n","-m","2000000000","-o",mousefilenamesorted,mousefilename)`

This appears to have fixed the error I was getting. I figured that I would share this so that others could fix this if they run into this problem with newer versions of samtools.

**Comment by mjafin** [comment]
Hi @bioinfomagician, many thanks for spotting this. We haven't used the intrinsic sorting facility in a long time as it's single threaded and thus slow. Would you mind preparing a pull request for your changes (to get your name in history)?

**Comment by bioinfomagician** [comment]
Hi @mjafin, thanks for the response. It makes sens that you'd want to do parallel sorting jobs to speed that step up. I put together a pull request with the changes I mentioned above.

**Comment by mjafin** [comment]
Thanks for this, much appreciated.
