### ISSUE TITLE
SAM validation error when running picard on disambiguated bam file

### ISSUE THREAD

**Issue by jrderuiter** [AstraZeneca-NGS/disambiguate#6]
When running picard MarkDuplicates on the disambiguated bam file, I get the following error:

```
Exception in thread "main" htsjdk.samtools.SAMFormatException: SAM validation error: ERROR: Record 898366, Read name HWI-ST867:205:C2MWWACXX:5:1315:5951:11990, bin field of BAM record does not equal value computed based on alignment start and end, and length of sequence to which read is aligned
```

This does not occur when running MarkDuplicates on the original bam file, indicating that the bam file that is produced by disambiguate is malformed. Running picard with lenient validation stringency circumvents the problem, but I don't know how downstream tools will be affected by this.

I am using the bioconda version of disambiguate.

**Comment by mjafin** [comment]
Hi @jrderuiter, Thanks for the report and sorry about the problem. Could you paste the same read from the pre-disambiguated BAM and disambiguated BAM? I just wonder if there is something obvious that we're doing wrong or if it's the API.

Further, are you using the python or C++ version?

**Comment by jrderuiter** [comment]
I'm using the C++ version. I also tried to use the C++ version to compare, but that gives me the following error:

```
Traceback (most recent call last):
  File "/home/j.d.ruiter/miniconda3/envs/snakemake/bin/disambiguate", line 11, in <module>
    load_entry_point('disambiguate==1.0', 'console_scripts', 'disambiguate')()
  File "/home/j.d.ruiter/miniconda3/envs/snakemake/lib/python3.6/site-packages/disambiguate.py", line 248, in main
    nexthumread=myHumanFile.next()
AttributeError: 'pysam.libcsamfile.Samfile' object has no attribute 'next'
```

Any idea why this occurs? Is it due to the pysam version or my python version? (I'm on Python 3.6).

This an example of one of the reads/alignments:

```
# From the original (human) alignment
HWI-ST867:205:C2MWWACXX:7:1201:8915:100160      117     X       9682945 0       *       =       9682945 0       AAGGGTGTACACTGTTCCTCCATAAACATCTATTTGATCAAGAAGCTTTCAAGCATACTGAAGTTAAAGAAATTACCATAAAAATCAATCTACTGCCACA CDCECDEEFD@FEHHHHIGJJIIHFGIJJIIHF@HJJJJJJJJIJJJIHJJJJJIIHJIJJJJJJJJJJJJJJIHJJJJJJJJJJJJHHHHFFFFFF@CBRG:Z:2503_1_T250_xenograft.L999  AS:i:0  XS:i:0
HWI-ST867:205:C2MWWACXX:7:1201:8915:100160      185     X       9682945 4       86M14S  =       9682945 0       GGAAGTCTCGTCCACAGCTACCGAGGAACAGGCGGCATATTTGAGGTGTGCTGGAATGCTCGAGGAGACAAAGTGGGTGCCAGCGCATCTGATGGCTCCG DDDDDBDDDDDDDDDDD@<DDDDDDDDDDDDDDFFFFFFHHHHHJJJIIHJIJIHGEIJJJJJJJJIJJJJJJIJJJJIJJJJJJJJHHHHHFFFFFCCBXA:Z:Y,-6958133,100M,12; MD:Z:4A3T17C2T8C2C14C2C26       RG:Z:2503_1_T250_xenograft.L999 NM:i:8  AS:i:47 XS:i:43

# From the disambiguate bam file
HWI-ST867:205:C2MWWACXX:7:1201:8915:100160      117     X       9682945 0       *       =       9682945 0       AAGGGTGTACACTGTTCCTCCATAAACATCTATTTGATCAAGAAGCTTTCAAGCATACTGAAGTTAAAGAAATTACCATAAAAATCAATCTACTGCCACA CDCECDEEFD@FEHHHHIGJJIIHFGIJJIIHF@HJJJJJJJJIJJJIHJJJJJIIHJIJJJJJJJJJJJJJJIHJJJJJJJJJJJJHHHHFFFFFF@CBAS:i:0   XS:i:0  RG:Z:2503_1_T250_xenograft.L999
HWI-ST867:205:C2MWWACXX:7:1201:8915:100160      185     X       9682945 4       86M14S  =       9682945 0       GGAAGTCTCGTCCACAGCTACCGAGGAACAGGCGGCATATTTGAGGTGTGCTGGAATGCTCGAGGAGACAAAGTGGGTGCCAGCGCATCTGATGGCTCCG DDDDDBDDDDDDDDDDD@<DDDDDDDDDDDDDDFFFFFFHHHHHJJJIIHJIJIHGEIJJJJJJJJIJJJJJJIJJJJIJJJJJJJJHHHHHFFFFFCCBXA:Z:Y,-6958133,100M,12; MD:Z:4A3T17C2T8C2C14C2C26       NM:i:8  AS:i:47 XS:i:43 RG:Z:2503_1_T250_xenograft.L999
```

**Comment by jrderuiter** [comment]
Also, I'm wondering if the statistics I'm seeing are correct. For a given normal sample, which should contain only human reads, I have the following statistics:

```
sample  unique species A pairs  unique species B pairs  ambiguous pairs
1957_13_N250    48002835        34829537        0
```

For me, it seems as if there are very many reads mapping to species B (mouse) for a human sample. Or am I interpreting these stats incorrectly?

**Comment by mjafin** [comment]
As the output of disambiguate is name sorted, you'll have to chr sort the files anyways and this problem should go away right? I haven't got any ideas on how to fix the bin field error. 

Which aligner are you using for the mapping? The number of ambiguous pairs being exactly zero is a bit suspicious - there might be a bug somewhere.

**Comment by jrderuiter** [comment]
I'm using BWA mem. 

For some reason, the sorting of the bam file (using picard SortSam or samtools) does not solve this issue. I think that the bin field is not modified by these tools. I think the bin field is rarely used in general, but still it would be nice if the error did not occur.

**Comment by jrderuiter** [comment]
I seem to have low numbers of amibiguous pairs for all my samples, which is strange:

```
# Human normal
sample  unique species A pairs  unique species B pairs  ambiguous pairs
1957_13_N250    48002835        34829537        0

# Human tumor
sample  unique species A pairs  unique species B pairs  ambiguous pairs
1957_6_T250     53066831        38574616        7

# Xenograft
sample  unique species A pairs  unique species B pairs  ambiguous pairs
2503_1_T250_xenograft   22489361        17733437        0
```

What can I do to debug the problem? I'm happy to take this discussion somewhere else if possible, as this is really unrelated to this issue.

**Comment by mjafin** [comment]
It would seem like the BamTools API may miscalculate the bin field sometimes: https://www.biostars.org/p/110004/ 

In the above table are the human normal, human tumor and xenograft all from the same sequencing run (i.e. same read length etc.)?

**Comment by jrderuiter** [comment]
Yes, I found that bamtools reference as well (although it seems to suggest that bamtools might be miscalculating the bin field, rather than confirming that it is). Should I open an issue there? 

The first two are from the same run, the third is from a later run. Read length is the same.

**Comment by mjafin** [comment]
Please do open a ticket with BamTools, that'd be great. We can update the package afterwards. 

If you used different captures or anything different at all in the lab that can cause differences in the alignment qualities, which are used for disambiguation. I'm open to suggestions on how to improve the algorithm; happy to accept any pull requests.

**Comment by jrderuiter** [comment]
I don't understand your last remark. As long as the same sequencing data is used for aligning to the mouse/human reference genomes, then disambiguation should work fine, right? How does the preparation of another sample affect the disambiguation?

**Comment by mjafin** [comment]
Sorry I was just referring to the high number of mouse assignments for the human-only samples in comparison to the real xenograft. Ideally for the human samples there'd be few mouse assignments but this depends on the quality of the alignments (which can be affected by many things like exome capture etc.). Does this make sense?

**Comment by jrderuiter** [comment]
Yes, however I'm still not entirely sure how to read the numbers. According to samtools flagstat, the bam file belonging to N250 has mapped 53791854 reads (with 99.94% mapped, which corresponds with ~26895927 pairs). Your summary suggests, that 48002835 reads are uniquely assigned to human, 34829537 reads are assigned to mouse and 0 reads are ambiguous. However, summed these numbers are greater than the total number of reads that flagstat reports.

**Comment by mjafin** [comment]
Got it. I will try to run some tests on my side this week to see if something is off.

**Comment by mjafin** [comment]
As an internal control I tend to run two publicly available samples through the algorithm, the SRR1930152 (mouse) and SRR387400 (human). I compared a run from 2015 (python) and a new one using the C++ algorithm. The changes are negligible so I don't think there is anything off in the C++ code as of late. Here are the assignments:
```
SRR387400 
      Disambiguated ambiguous reads: 9454691
      Disambiguated hg38 reads: 50114672
      Disambiguated mm10 reads: 83707
SRR1930152 
      Disambiguated ambiguous reads: 703039
      Disambiguated hg38 reads: 35345
      Disambiguated mm10 reads: 23317760
```
I did the analysis via bcbio-nextgen, for which we pull the disambiguation algorithm from bioconda. 

As for the Python package, could you try running it in Python 2.7 (e.g. via anaconda+bioconda)?

**Comment by jrderuiter** [comment]
Ok, strange. I'll compare with the bcbio-nextgen pipeline to see what we're doing differently. I'll also have a look at Python 2.7.

**Comment by jrderuiter** [comment]
Which settings do you use for bcbio?

I ran the same sample (SRR387400) through bcbio for comparison and get the following stats:

```
      Disambiguated ambiguous reads: 3729187
      Disambiguated hg38 reads: 55525841
      Disambiguated mm10 reads: 398042
```

For this I used the following settings:

```
details:
- algorithm:
    aligner: bwa
    mark_duplicates: true
    realign: false
    recalibrate: false
    variantcaller: freebayes
    disambiguate: [mm10]
  analysis: variant2
  description: SRR387400
  files:
  - /DATA/scratch/j.d.ruiter/bcbio/scratch/test/input/SRR387400_1.fastq.gz
  - /DATA/scratch/j.d.ruiter/bcbio/scratch/test/input/SRR387400_2.fastq.gz
  genome_build: hg38
fc_date: '2017-06-22'
fc_name: test
upload:
  dir: ../final
```

**Comment by mjafin** [comment]
I actually used Hisat2 with hg38. Looks like bwa is doing a much better job on RNA-seq :)

As an aside I do think Hisat2 needs a lot of work. It seems to e.g. produce a lot of short indels that I don't think are real.

**Comment by jrderuiter** [comment]
Ah, that explains things. I didn't realize this was RNAseq data, thanks! I'll try comparing the bcbio results with my own pipeline to see where things are going wrong.

**Comment by jrderuiter** [comment]
I think I found the issue in my pipeline. I initially used picard to sort and merge bam files from multiple lanes, before doing the disambiguation. However, picard sorts differently than samtools when sorting by queryname (https://www.biostars.org/p/102735/). Your software (judging from the Python version) uses the same natural sort that samtools uses, which I think is not compatible with the sorting produced by picard.

I seem to have solved the issue by first sorting the alignment from bwa with samtools, then doing the disambiguation and then sorting and merging the bam files. 

If this is indeed the underlying issue, I think it would be good to stress your software is incompatible with name-sorted bams from tools other than samtools/sambamba. 

Just out of curiosity, does the '-M' flag for bwa affect the results from disambiguate? (This is a flag that I haven't used in this experiment, but which is passed by bcbio-nextgen.)

**Comment by mjafin** [comment]
Got it, we should be more explicit about that. There is a related issue explaining the problem here https://github.com/chapmanb/bcbio-nextgen/issues/821 , i.e. natural name sorting needs to be used. 

The `-M` flag for bwa should not affect the results as we do not pay attention to whether the alignments are primary/secondary/complementary. For all alignments of a single read, the highest quality one is used in disambiguation. By highest quality I mean the score we give to the read (it's slightly different for bwa/star vs tophat/hisat).

**Comment by jrderuiter** [comment]
Is the requirement for natural sorting strictly necessary? I wouldn't expect the exact sorting algorithm to be important, as long as the bam files are sorted in the same way.

**Comment by mjafin** [comment]
It actually is, see https://github.com/AstraZeneca-NGS/disambiguate/blob/master/disambiguate.py#L33 and the usage of the function. The analysis in disambiguation needs to match the sorting algorithm that was originally used for the bam files and the initial implementation was based on samtools output. While it would be in theory possibly to define other comparison functions to support also e.g. lexicographic name sorting we haven't gone down that route.
