### ISSUE TITLE
Minimum System Requirements

### ISSUE THREAD

**Issue by dwent** [AstraZeneca-NGS/disambiguate#7]
Could you recommend a minimum system requirements for disambiguate? 
The important information included operating systems, memory, CPU cores number and storage. It's even better to be able to provide dependent softwares.
Looking forward to your reply, thanks.

**Comment by chapmanb** [comment]
Thanks for the question. The `ngs_disambiguate` executable requires BAM files prepared with one of the supported aligners (https://github.com/AstraZeneca-NGS/disambiguate/blob/master/README.md). Storage requirements will depend on the input BAM size, but estimate 2 times the initial BAM size. It uses a single core, 4Gb of memory and will run on any Linux/Unix style operating system. We recommend installing using bioconda (https://bioconda.github.io/). Hope this helps.
