### ISSUE TITLE
pysam.libcsamfile.Samfile object has no attribute 'next'

### ISSUE THREAD

**Issue by bwubb** [AstraZeneca-NGS/disambiguate#8]
Greetings,

```
Traceback (most recent call last):
  File "/home/bwubb/software/disambiguate/disambiguate.py", line 351, in <module>
    main()
  File "/home/bwubb/software/disambiguate/disambiguate.py", line 248, in main
    nexthumread=myHumanFile.next()
AttributeError: 'pysam.libcsamfile.Samfile' object has no attribute 'next'
```

  I suppose this is a python 3+ issue, but the python script is now "broken". I think all of the myHumanFile.next() need to become next(myHumanFile).

edit: I think 'myHumanFile.\_\_next\_\_()' would also work.

**Comment by mjafin** [comment]
@bwubb thanks for reporting the issue. Just to confirm, you're using Python 3? I haven't tested Disambiguate on Python 3 at all. Would it be possible for you to run Disambiguate using Python 2 by any chance? Miniconda/bioconda are my recommendations.

**Comment by bwubb** [comment]
@mjafin I am currently using python3. I did a fast `sed -i '/next()/__next__()/g' disambiguate.py` without caution. Everything worked fine for me. I retested in with python2 and it still worked. I believe `__next__()` is backwards compatible. I just have not yet made a pull request because I am a bad git-hubber
