### ISSUE TITLE
Segmentation fault and pysam errors

### ISSUE THREAD

**Issue by jsmedmar** [AstraZeneca-NGS/disambiguate#9]
@roryk we are currently using your tool and found some issues with the python implementation. We fixed a segmentation fault (reproducible by just running the test samples). Also fixed pysam compatibility errors with `.next()`. We added CI testing and coverage evaluation for both Python 2 and Python 3, I'm planning to release a frozen version to pypi as `_disambiguate` (of course under the name of the original authors). I gave you write permissions to the [repo](https://github.com/leukgen/disambiguate), check the [diff](https://github.com/AstraZeneca-NGS/disambiguate/compare/master...leukgen:master?expand=1).

**Comment by jsmedmar** [comment]
The lines that produced the segmentation error where these:

- https://github.com/AstraZeneca-NGS/disambiguate/blob/master/disambiguate.py#L286 
- https://github.com/AstraZeneca-NGS/disambiguate/blob/master/disambiguate.py#L290

We simply replaced 

```python
if nexthumread == None:
    EOFhuman = True
```

For: 

```python
if not nexthumread:
    EOFhuman = True
```

**Comment by chapmanb** [comment]
Thanks for the report and the bug fix. We've been primarily using the C++ version so appreciate your help keeping this up to date. Would you be able to submit a pull request with your fix so we can give you proper credit in the repository history for the fix? Thanks again.

**Comment by jsmedmar** [comment]
Ok will do, would you be interested in tox tests and continuous integration configuration with travis?

**Comment by jsmedmar** [comment]
Travis is very simple to set up and will be a great addition to the project, you could also automate the deployment to `pypi` at some point and tests for the cpp implementation.

**Comment by roryk** [comment]
+1 for CI and tests. Thanks so much.

**Comment by MattBashton** [comment]
Did this fix get pushed, because attempting to use a freshly cloned version on Ubuntu 16.04 fails with the segmentation bug:

`disambiguate.py test/human.bam test/mouse.bam
Segmentation fault (core dumped)`

**Comment by mjafin** [comment]
I just pushed the above fix, apologies for the delay. Please let me know if it gets your data processed OK.
